### ISSUE TITLE
[Tests] Convert mocha tests to tape

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/ua#6]
switch to tape and use travis

**Comment by shawninder** [comment]
Travis is setup but is failing (something to do with a missing slack environment variable).

@DanilloCorvalan Could you check this out? We don't want to fail when slack is not set up, because that is not an indication of wether the module is in a usable state or not. Perhaps we can just have a warning?

Also, maybe it's good for you to convert the tests to `tape` so you get a chance to familiarize yourself with it?
